language: python

# test against multiple versions
python:
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install: 
  - "pip install -e ."
  - "pip install pytest-cov coveralls"

# command to run tests
script: "py.test --cov-report= --cov=whydtogo"

# deploy on pypi
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_cleanup: true
  on:
    tags: true
    branch: master
    python: "3.5"
